<div id="MenuDown">
	<ul>
	<?php include('core/menu.inc') ?>
	</ul>
</div>
<div class="FooterLogo"><a href="http://www.elgrande.su"><img src="/images/gif.gif" width="162px" height="106px"></a></div>
<div class="FooterText">Так же Вы можете заказать 21 вид итальянской пиццы</div>
<div class="FooterText1">Полный ассортимент блюд и напитков уточняйте у оператора. В заказ входят имбирь, соус, васаби и палочки. Вес продукта указан до его приготовления. Все права защищены. Использование фотоматериалов и элементов фирменного стиля компании преследуется по закону.</div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17954503-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//v2.zopim.com/?1wL8a0UMOLIbvMBzVZrwBBOBgBcKoUvR';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter17284471 = new Ya.Metrika({id:17284471, enableAll: true, webvisor:true});
        } catch(e) { }
    });
    
    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/17284471" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<!-- code from Daria-->
<script type="text/javascript">(window.Image ? (new Image()) : document.createElement('img')).src = location.protocol + '//vk.com/rtrg?r=VQ2dEeWBCbHuduInUiUDJsFXZpjmACK1*XA/tDPm7wKER8YJPChfW2WJWeStvRDcJp7IigBaOqw3E3RfwE5VwZoAOUNuFjRpH*r6F/76w64cnWn1rfGFO3hIroHRZy290JaCd7m/QTefU4QJdNxTtCBrLs2fv5w0gLVwJmttMPQ-';</script>
<!-- /code from Daria-->
