<div id="MenuDown">
	<ul>
	<?php include('core/menu.inc') ?>
	</ul>
</div>
<div class="FooterLogo"><a href="http://www.elgrande.su"><img src="/images/gif.gif" width="162px" height="106px"></a></div>
<div class="FooterText">Так же Вы можете заказать 21 вид итальянской пиццы</div>
<div class="FooterText1">Полный ассортимент блюд и напитков уточняйте у оператора. В заказ входят имбирь, соус, васаби и палочки. Вес продукта указан до его приготовления. Все права защищены. Использование фотоматериалов и элементов фирменного стиля компании преследуется по закону.</div>





