<a class="Logo" href="/" title="BigFish"></a>
<a class="vk1" href="https://vk.com/app4602210#2627-welcome" title="BigFish"></a>
<ul>
	<li><a class="Menu-15" href="/action.php"><b>АКЦИИ</b></a></li>
	<li><a class="Menu-14" href="/news.php"><b>НОВОСТИ</b></a></li>
	<li><a class="Menu-11" href="/about.php"><b>О КОМПАНИИ</b></a></li>
	<li><a class="Menu-12" href="/delivery.php"><b>РАЙОНЫ и ДОСТАВКА</b></a></li>
	<li><a class="Menu-13" href="/contacts.php"><b>КОНТАКТЫ</b></a></li>
	
</ul>
<div class="skorovcao"></div>
<div class="online"></div>
<div class="skidon"></div>
<div class="vk">


<script type="text/javascript" src="//yandex.st/share/share.js"
charset="utf-8"></script>
<div class="yashare-auto-init" data-yashareL10n="ru"
 data-yashareType="none" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir,lj,gplus"

></div></div> 






<h1>БОЛЬШОЙ ВЫБОР БОЛЬШИХ РОЛЛОВ</h1>
<dl>Мы работаем с <b>10:30</b> до <b>23:30</b> Пятница, суббота, воскресенье и предпраздничные дни до <b>00:00</b></dl>
<dt>Многоканальный телефон единой службы доставки <a href='tel:9700000'>9700000</a></dt>