<li><a class="Menu-1" href="/?cat=1"><b>СУШИ</b></a></li>
<li><a class="Menu-2" href="/"><b>РОЛЛЫ</b></a></li>
<li><a class="Menu-3" href="/?cat=3"><b>САШИМИ</b></a></li>
<li><a class="Menu-4" href="/?cat=4"><b>САЛАТЫ</b></a></li>
<li><a class="Menu-5" href="/?cat=5"><b>ГОРЯЧЕЕ</b></a></li>
<li><a class="Menu-6" href="/?cat=6"><b>ДЕСЕРТЫ</b></a></li>
<li><a class="Menu-7" href="/?cat=7"><b>АССОРТИ</b></a></li>
<li><a class="Menu-8" href="/?cat=8"><b>ДОПОЛНИТЕЛЬНО</b></a></li>
<li><a class="Menu-9" href="/?cat=9"><b>НАПИТКИ</b></a></li>
<li><a class="Menu-10" href="/?cat=10"><b>ПИЦЦА&nbsp;&nbsp;</b></a></li>
<li><a class="Menu-31" href="/?cat=11"><b>BIG-ЛАНЧ&nbsp;</b></a></li>
<li><a class="Menu-32" href="/?cat=16"><b>BIG-WOK</b></a></li>
<li><a class="Menu-33" href="/article/" style="margin-left: 5px;"><b>БЛОГ</b></a></li>



