<!-- Block 1 -->
<div class="Products">
<div class="Title" name="1">
	<h1>СОКИ</h1>
	<ul>
		<li><a href="#2">прохладительные</a></li>
		<li><a href="#3">слабоалкогольные</a></li>
	</ul>
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_1_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_nap" />
			<input type="hidden" name="my-item-name" value="Яблочный сок" />
			<input type="hidden" name="my-item-price" value="130" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/1_nap.jpg"></div>
			<h3>Яблочный сок</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>130 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_nap" />
			<input type="hidden" name="my-item-name" value="Вишневый сок" />
			<input type="hidden" name="my-item-price" value="130" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/2_nap.jpg"></div>
			<h3>Вишневый сок</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>130 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_3_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_nap" />
			<input type="hidden" name="my-item-name" value="Апельсиновый сок" />
			<input type="hidden" name="my-item-price" value="130" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/3_nap.jpg"></div>
			<h3>Апельсиновый сок</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>130 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_nap" />
			<input type="hidden" name="my-item-name" value="Томатный сок" />
			<input type="hidden" name="my-item-price" value="130" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/4_nap.jpg"></div>
			<h3>Томатный сок</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>130 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_15_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="15_nap" />
			<input type="hidden" name="my-item-name" value="Мультифрукт" />
			<input type="hidden" name="my-item-price" value="130" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/15_nap.jpg"></div>
			<h3>Мультифрукт</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>130 р.</b></span>		
		</form>
	</li>
	
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 1 -->

<!-- Block 2 -->
<div class="Products">
<div class="Title" name="2">
	<h1>ПРОХЛАДИТЕЛЬНЫЕ</h1>
	<ul>
		<li><a href="#1">соки</a></li>
		<li><a href="#3">слабоалкогольные</a></li>	</ul>
</div>
<!-- ITEMS -->
<ul class="Items">
 <li>
		<form method="post" action="" class="jcart" id="Item_vivo2_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="vivo2_nap" />
			<input type="hidden" name="my-item-name" value="Напиток с соком Алоэ Вера" />
			<input type="hidden" name="my-item-price" value="100" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/vivo2_nap.jpg"></div>
			<h3>Напиток с соком и кусочками Алоэ Вера</h3>
			<p></br><b class="veskal">350 мл.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>100 р.</b></span>		
		</form><dd class="newhit3">
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_vivo1_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="vivo1_nap" />
			<input type="hidden" name="my-item-name" value="Напиток с соком Маракуйи и мёдом" />
			<input type="hidden" name="my-item-price" value="100" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/vivo1_nap.jpg"></div>
			<h3>Напиток с соком Маракуйи и мёдом</h3>
			<p></br><b class="veskal">350 мл.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>100 р.</b></span>		
		</form><dd class="newhit3">
	</li>
    
	<li>
		<form method="post" action="" class="jcart" id="Item_5_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000285" />
			<input type="hidden" name="my-item-name" value="Бонаква без газа" />
			<input type="hidden" name="my-item-price" value="65" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/5_nap.jpg"></div>
			<h3>Бонаква без газа</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>65 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_6_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000283" />
			<input type="hidden" name="my-item-name" value="Бонаква газированная" />
			<input type="hidden" name="my-item-price" value="65" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/6_nap.jpg"></div>
			<h3>Бонаква газированная</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>65 р.</b></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_7_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000281" />
			<input type="hidden" name="my-item-name" value="Фанта" />
			<input type="hidden" name="my-item-price" value="90" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/7_nap.jpg"></div>
			<h3>Фанта</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>90 р.</b></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_8_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000280" />
			<input type="hidden" name="my-item-name" value="Кока-кола" />
			<input type="hidden" name="my-item-price" value="90" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/8_nap.jpg"></div>
			<h3>Кока-кола</h3>
	    	<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>90 р.</b></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_9_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000282" />
			<input type="hidden" name="my-item-name" value="Спрайт" />
			<input type="hidden" name="my-item-price" value="90" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/9_nap.jpg"></div>
			<h3>Спрайт</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>90 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_16_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000294" />
			<input type="hidden" name="my-item-name" value="Нести Лесная ягода" />
			<input type="hidden" name="my-item-price" value="100" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/16_nap.jpg"></div>
			<h3>Нести Лесная ягода</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>100 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_17_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000295" />
			<input type="hidden" name="my-item-name" value="Нести Зеленый чай" />
			<input type="hidden" name="my-item-price" value="100" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/17_nap.jpg"></div>
			<h3>Нести Зеленый чай</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>100 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_18_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000296" />
			<input type="hidden" name="my-item-name" value="Нести персик" />
			<input type="hidden" name="my-item-price" value="100" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/18_nap.jpg"></div>
			<h3>Нести персик</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>100 р.</b></span>		
		</form>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_20_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000286" />
			<input type="hidden" name="my-item-name" value="Морс вишнёвый" />
			<input type="hidden" name="my-item-price" value="100" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/20_nap.jpg"></div>
			<h3>Морс вишнёвый</h3>
			<p></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>100 р.</b></span>		
		</form>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_21_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000287" />
			<input type="hidden" name="my-item-name" value="Морс виноград, черника, клюква" />
			<input type="hidden" name="my-item-price" value="100" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/21_nap.jpg"></div>
			<h3>Морс виноград, черника, клюква</h3>
			<p></br></br><b class="veskal">1 литр</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>100 р.</b></span>		
		</form>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_burn_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="burn_nap" />
			<input type="hidden" name="my-item-name" value="Burn - напиток энергетический" />
			<input type="hidden" name="my-item-price" value="120" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/burn_nap.jpg"></div>
			<h3>Burn - напиток энергетический</h3>
			<p></br></br><b class="veskal">0,33 литра</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>120 р.</b></span>		
		</form>
	</li>
	
	<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 2 -->

<!-- Block 3 -->
<div class="Products">
<div class="Title" name="3">
	<h1>СЛАБОАЛКОГОЛЬНЫЕ</h1>
	<ul>
		<li><a href="#1">соки</a></li>
		<li><a href="#2">прохладительные</a></li>
	</ul>
</div>
<!-- ITEMS -->
<ul class="Items">
<li>
		<form method="post" action="" class="jcart" id="Item_amber_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="amber_nap" />
			<input type="hidden" name="my-item-name" value="AmberWeiss" />
			<input type="hidden" name="my-item-price" value="120" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/amber_nap.jpg"></div>
			<h3>AmberWeiss</h3>
			<p></br><b class="veskal">0,45 литра, светлое нефильтрованное</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>120 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_13_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="13_nap" />
			<input type="hidden" name="my-item-name" value="Старый мельник" />
			<input type="hidden" name="my-item-price" value="70" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/13_nap.jpg"></div>
			<h3>Старый мельник</h3>
			<p></br><b class="veskal">0,5 литра</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>70 р.</b></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_14_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="14_nap" />
			<input type="hidden" name="my-item-name" value="Эфес" />
			<input type="hidden" name="my-item-price" value="70" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/14_nap.jpg"></div>
			<h3>Эфес</h3>
			<p></br><b class="veskal">0,5 литра</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>70 р.</b></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_10_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="10_nap" />
			<input type="hidden" name="my-item-name" value="Бавария светлое" />
			<input type="hidden" name="my-item-price" value="90" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/10_nap.jpg"></div>
			<h3>Бавария светлое</h3>
			<p></br><b class="veskal">0,5 литра</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>90 р.</b></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_112_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="112_nap" />
			<input type="hidden" name="my-item-name" value="Бавария Мальт безалк." />
			<input type="hidden" name="my-item-price" value="100" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/112_nap.jpg"></div>
			<h3>Бавария Мальт безалк.</h3>
			<p></br><b class="veskal">0,5 литра</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>100 р.</b></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_113_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="113_nap" />
			<input type="hidden" name="my-item-name" value="Козел тёмное" />
			<input type="hidden" name="my-item-price" value="100" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/113_nap.jpg"></div>
			<h3>Козел тёмное</h3>
			<p></br><b class="veskal">0,5 литра</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>100 р.</b></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_111_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="111_nap" />
			<input type="hidden" name="my-item-name" value="Пилснер урквел" />
			<input type="hidden" name="my-item-price" value="110" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/111_nap.jpg"></div>
			<h3>Пилснер Урквел</h3>
			<p></br><b class="veskal">0,5 литра</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>110 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_19_nap">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="19_nap" />
			<input type="hidden" name="my-item-name" value="Тан Фунг Саке" />
			<input type="hidden" name="my-item-price" value="1300" />
			<input type="hidden" name="my-item-url" value="/catalog/nap/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/nap/19_nap.jpg"></div>
			<h3>Тан Фунг Саке</h3>
			<p></br><b class="veskal">0,75 литра</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>1300 р.</b></span>		
		</form>
	</li><br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 3 -->
