<!-- САЛАТЫ -->

<!-- Block 1 -->
<div class="Products">
<div class="Title" name="1">
	<h1>САЛАТЫ</h1>
	
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_1_sal">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_sal" />
			<input type="hidden" name="my-item-name" value="Цезарь с креветками" />
			<input type="hidden" name="my-item-price" value="220" />
			<input type="hidden" name="my-item-url" value="/catalog/salat/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/salat/1_sal.jpg"></div>
			<h3>Цезарь с креветками</h3>
			<p>Тигровые креветки, салат айс-берг, сухарики, сыр пармезан, соус Цезарь, томаты Черри.</br><b class="veskal">220 г., 250 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>220 р.</b></span>		
		</form><dd class="newhit4"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_sal">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_sal" />
			<input type="hidden" name="my-item-name" value="Цезарь с лососем" />
			<input type="hidden" name="my-item-price" value="220" />
			<input type="hidden" name="my-item-url" value="/catalog/salat/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/salat/2_sal.jpg"></div>
			<h3>Цезарь с лососем</h3>
			<p>Норвежский лосось, салат айс-берг, сухарики, сыр пармезан, соус Цезарь, томаты Черри.</br><b class="veskal">220 г., 210 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>220 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_3_sal">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_sal" />
			<input type="hidden" name="my-item-name" value="Цезарь с курицей" />
			<input type="hidden" name="my-item-price" value="220" />
			<input type="hidden" name="my-item-url" value="/catalog/salat/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/salat/3_sal.jpg"></div>
			<h3>Цезарь с курицей</h3>
			<p>Филе курицы, салат айсберг, сухарики, сыр пармезан, соус Цезарь, томаты Черри.</br><b class="veskal">220 г., 205 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>220 р.</b></span>		
		</form><dd class="newhit4"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_sal">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_sal" />
			<input type="hidden" name="my-item-name" value="Греческий" />
			<input type="hidden" name="my-item-price" value="200" />
			<input type="hidden" name="my-item-url" value="/catalog/salat/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/salat/4_sal.jpg"></div>
			<h3>Греческий</h3>
			<p>Помидоры, огурцы, маслины, брынза, оливковое масло, лук.</br><b class="veskal">280 г., 203 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>200 р.</b></span>		
		</form><dd class="newhit5"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_5_sal">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_sal" />
			<input type="hidden" name="my-item-name" value="Чука с ореховым соусом" />
			<input type="hidden" name="my-item-price" value="180" />
			<input type="hidden" name="my-item-url" value="/catalog/salat/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/salat/5_sal.jpg"></div>
			<h3>Чука с ореховым соусом</h3>
			<p>Морские водоросли чука, ореховый соус.</br><b class="veskal">100 г., 160 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>180 р.</b></span>		
		</form><dd class="newhit5"></dd>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_8_sal">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="8_sal" />
			<input type="hidden" name="my-item-name" value="Чука с угрем" />
			<input type="hidden" name="my-item-price" value="300" />
			<input type="hidden" name="my-item-url" value="/catalog/salat/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/salat/8_sal.jpg"></div>
			<h3>Чука с угрем</h3>
			<p>Морские водоросли чука, угорь, соус ореховый и унаги-маки.</br><b class="veskal">220 г., 260 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>300 р.</b></span>		
		</form><dd class="newhit5"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_6_sal">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="6_sal" />
			<input type="hidden" name="my-item-name" value="Овощной" />
			<input type="hidden" name="my-item-price" value="180" />
			<input type="hidden" name="my-item-url" value="/catalog/salat/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/salat/6_sal.jpg"></div>
			<h3>Овощной</h3>
			<p>Помидор, огурец, болгарский перец, лук, салат айсберг, оливковое масло</br><b class="veskal">320 г., 170 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>180 р.</b></span>		
		</form><dd class="newhit5"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_7_sal">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="7_sal" />
			<input type="hidden" name="my-item-name" value="Калипсо" />
			<input type="hidden" name="my-item-price" value="250" />
			<input type="hidden" name="my-item-url" value="/catalog/salat/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/salat/7_sal.jpg"></div>
			<h3>Калипсо</h3>
			<p>Креветка, салат айсберг, авокадо, помидоры.</br><b class="veskal">220 г., 260 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>250 р.</b></span>		
		</form><dd class="newhit1"></dd>
	</li>
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 1 -->
