<!-- САЛАТЫ -->

<!-- Block 1 -->
<div class="Products">
<div class="Title" name="1">
	<div class="commbl"><nobr>Доставка Big-ланчей осуществляется с понедельника по пятницу с 12 до 16 часов.</nobr></div>
	<div class="commbl2"><nobr>Доставка с понедельника по пятницу с 12 до 16 часов.</nobr></div>
	
	<h1>BIG-ЛАНЧИ</h1>
	
</div>
<!-- ITEMS -->

<ul class="Items Big">
	<li>
		<form method="post" action="" class="jcart" id="Item_bl1">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="bl1" />
			<input type="hidden" name="my-item-name" value="Big-ланч 1" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/bl/" />
			<input class="qty blq" type="text" name="my-item-qty" value="2"/>
			<div ><img class="bl" src="/catalog/bl/bl1.jpg"></div>
			<h3 class="bltitle">BIG-ЛАНЧ 1</h3>
			<p class="blp"></br></br>
			<b class="blzagl">Суп Мисо</b><b class="veskal1"> (200 гр.)(сыр тофу, грибы намэко, кунжут, мисо паста, морские водоросли, зел. лук)</b></br>
			<b class="blzagl">Ролл Бостон</b><b class="veskal1"> (105 гр.)(тигровая креветка, огурец, сыр филадельфия)</b></br>
			<b class="blzagl">Рис с обжаренными овощами </b><b class="veskal1"> (150 гр.)(рис, овощи, зелёный лук, перец сладкий, чеснок, масло кунжутное и растительное, соевый соус, кунжут)</b></br>
			<b class="blzagl">Сок RICH</b><b class="veskal1">(0,2 л.) (яблоко, вишня, апельсин, мультифрукт, томат)</b></br>
			<b class="blzagl">Имбирь, васаби, соевый соус </b></br>
			
			</p>
			<span class="blspan"><input type="submit" name="my-add-button" value=" " class="AddCartbl"/>Цена: <b>285 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_bl2">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="bl2" />
			<input type="hidden" name="my-item-name" value="Big-ланч 2" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/bl/" />
			<input class="qty blq" type="text" name="my-item-qty" value="2"/>
			<div ><img class="bl" src="/catalog/bl/bl2.jpg"></div>
			<h3 class="bltitle">BIG-ЛАНЧ 2</h3>
			<p class="blp"></br></br>
			<b class="blzagl">Суп c лососем</b><b class="veskal1"> (200 гр.)(лосось, салат айсберг, грибы шамп., соевый соус, зел. лук)</b></br>
			<b class="blzagl">Ролл Чикаго</b><b class="veskal1"> (105 гр.)(лосось, тунец, огурец, сыр филадельфия, кунжут)</b></br>
			<b class="blzagl">Рис с обжаренными морепродуктами </b><b class="veskal1"> (150 гр.)(рис, гребешок, кальмар, тигр. креветка, окунь, осьминог, перец, чеснок, лук, лимон, кунжут, масло растит., соевый соус)</b></br>
			<b class="blzagl">Сок RICH</b><b class="veskal1"> (0,2 л.) (яблоко, вишня, апельсин, мультифрукт, томат)</b></br>
			<b class="blzagl">Имбирь, васаби, соевый соус </b></br>
			
			</p>
			<span class="blspan"><input type="submit" name="my-add-button" value=" " class="AddCartbl"/>Цена: <b>285 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_bl3">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="bl3" />
			<input type="hidden" name="my-item-name" value="Big-ланч 3" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/bl/" />
			<input class="qty blq" type="text" name="my-item-qty" value="2"/>
			<div ><img class="bl" src="/catalog/bl/bl3.jpg"></div>
			<h3 class="bltitle">BIG-ЛАНЧ 3</h3>
			<p class="blp"></br></br>
			<b class="blzagl">Суп суимоно</b><b class="veskal1"> (200 гр.)(бульон суимоно, лосось, окунь, осьминог, креветка, кальмар, гребешок, рис, кунжут)</b></br>
			<b class="blzagl">Ролл Камчатка</b><b class="veskal1"> (108 гр.)(тигровая креветка, филадельфия, копчёный лосось, тобико, авокадо, огурец)</b></br>
			<b class="blzagl">Шашлычок Креветка</b><b class="veskal1"> (40 гр.) (креветка тигровая, лук порей)</b></br>
			<b class="blzagl">Сок RICH</b><b class="veskal1"> (0,2 л.) (яблоко, вишня, апельсин, мультифрукт, томат)</b></br>
			<b class="blzagl">Имбирь, васаби, соевый соус </b></br>
			
			</p>
			<span class="blspan"><input type="submit" name="my-add-button" value=" " class="AddCartbl"/>Цена: <b>285 р.</b></span>		
		</form>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_bl4">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="bl4" />
			<input type="hidden" name="my-item-name" value="Big-ланч 4" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/bl/" />
			<input class="qty blq" type="text" name="my-item-qty" value="2"/>
			<div ><img class="bl" src="/catalog/bl/bl4.jpg"></div>
			<h3 class="bltitle">BIG-ЛАНЧ 4</h3>
			<p class="blp"></br></br>
			<b class="blzagl">Пицца Маргарита</b><b class="veskal1"> (175 гр.) (соус el’Grande, сыр моццарелла, сыр пармезан, помидоры, базилик)</b></br>
			<b class="blzagl">Картофель “Фри” </b><b class="veskal1"> (палочки картофеля, обжаренного во фритюрном масле, соль)</b></br>
			<b class="blzagl">Цезарь с курицей</b><b class="veskal1"> (110 гр.)(обжаренная курица, салат айсберг, сыр пармезан, помидоры черри, соус цезарь,сухарики, лимонный сок)</b></br>
			<b class="blzagl">Сок RICH</b><b class="veskal1"> (0,2 л.) (яблоко, вишня, апельсин, мультифрукт, томат)</b></br>
			<b class="blzagl">Соус томатный </b></br>
			
			</p>
			<span class="blspan"><input type="submit" name="my-add-button" value=" " class="AddCartbl"/>Цена: <b>285 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_bl5">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="bl5" />
			<input type="hidden" name="my-item-name" value="Big-ланч 5" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/bl/" />
			<input class="qty blq" type="text" name="my-item-qty" value="2"/>
			<div ><img class="bl" src="/catalog/bl/bl5.jpg"></div>
			<h3 class="bltitle">BIG-ЛАНЧ 5</h3>
			<p class="blp"></br></br>
			<b class="blzagl">Пицца Венская</b><b class="veskal1"> (188 гр.) (соус el’Grande, сыр моццарелла, сыр швейцарский, сыр пармезан, сосиски венские отборные)</b></br>
			<b class="blzagl">Картофель “По-деревенски”</b><b class="veskal1"> (150 гр.)(дольки картофеля, обжаренного во фритюрном масле, специи)</b></br>
			<b class="blzagl">Салат “Греческий”</b><b class="veskal1"> (120 гр.)
(сыр фетакса, салат айсберг, 
помидор, перец сладкий, 
огурец, маслины, лук репч.,
масло оливковое, лимон. сок)</b></br>
			<b class="blzagl">Сок RICH</b><b class="veskal1"> (0,2 л.) (яблоко, вишня, апельсин, мультифрукт, томат)</b></br>
			<b class="blzagl">Соус томатный </b></br>
			
			</p>
			<span class="blspan"><input type="submit" name="my-add-button" value=" " class="AddCartbl"/>Цена: <b>285 р.</b></span>		
		</form>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_bl6">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="bl6" />
			<input type="hidden" name="my-item-name" value="Big-ланч 6" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/bl/" />
			<input class="qty blq" type="text" name="my-item-qty" value="2"/>
			<div ><img class="bl" src="/catalog/bl/bl6.jpg"></div>
			<h3 class="bltitle">BIG-ЛАНЧ 6</h3>
			<p class="blp"></br></br>
			<b class="blzagl">Пицца Маргарита </b><b class="veskal1"> (175 гр.) 
(соус el’Grande, сыр моццарелла, 
сыр пармезан, помидоры, 
базилик)</b></br>
			<b class="blzagl">Крылья “Баффало”</b><b class="veskal1"> (250 гр.)
(маринованные куриные 
крылышки, приготовленные 
во фритюрном масле)</b></br>
			<b class="blzagl">Салат “Овощной”  </b><b class="veskal1"> (120 гр.)
(огурец, перец болгарский, 
помидор, салат айсберг, 
лук репчатый, лимонный сок,
масло оливковое)</b></br>

			<b class="blzagl">Сок RICH</b><b class="veskal1"> (0,2 л.) (яблоко, вишня, апельсин, мультифрукт, томат)</b></br>
			<b class="blzagl">Соус томатный </b></br>
			
			</p>
			<span class="blspan"><input type="submit" name="my-add-button" value=" " class="AddCartbl"/>Цена: <b>285 р.</b></span>		
		</form>
	</li>
	
	<br class="Clear" />	
</ul><dd class="blpolosa2"></dd><b class="veskal2">Минимальный заказ на 2 персоны. Скидки и акции на Big-ланчи не распостраняются.</b>
<!-- /ITEMS -->
</div>
<dd class="blpolosa1"></dd><!-- /Block 1 -->
