<!-- ДЕСЕРТЫ -->


<!-- Block 1 -->
<div class="Products">
<div class="Title" name="1">

<h1>ДЕСЕРТЫ</h1>
	<ul>
	<li><a href="#2">сладкие роллы</a></li>
		<li><a href="#3"></a></li>
		
	</ul>
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_13_slad">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="13_slad" />
			<input type="hidden" name="my-item-name" value="Чизкейк" />
			<input type="hidden" name="my-item-price" value="220" />
			<input type="hidden" name="my-item-url" value="/catalog/desert/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/desert/13_slad.jpg"></div>
			<h3>Чизкейк</h3>
			<p></br><b class="veskal">150 г., 230 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>220 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_12_slad">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="12_slad" />
			<input type="hidden" name="my-item-name" value="Милфей" />
			<input type="hidden" name="my-item-price" value="220" />
			<input type="hidden" name="my-item-url" value="/catalog/desert/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/desert/12_slad.jpg"></div>
			<h3>Милфей</h3>
			<p></br><b class="veskal">150 г., 230 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>220 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_11_slad">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="11_slad" />
			<input type="hidden" name="my-item-name" value="Медовик" />
			<input type="hidden" name="my-item-price" value="220" />
			<input type="hidden" name="my-item-url" value="/catalog/desert/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/desert/11_slad.jpg"></div>
			<h3>Медовик</h3>
			<p></br><b class="veskal">150 г., 230 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>220 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_15_slad">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="15_slad" />
			<input type="hidden" name="my-item-name" value="Карамельный" />
			<input type="hidden" name="my-item-price" value="220" />
			<input type="hidden" name="my-item-url" value="/catalog/desert/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/desert/15_slad.jpg"></div>
			<h3>Карамельный</h3>
			<p></br><b class="veskal">130 г., 230 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>220 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_14_slad">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="14_slad" />
			<input type="hidden" name="my-item-name" value="Манго-маракуйя" />
			<input type="hidden" name="my-item-price" value="220" />
			<input type="hidden" name="my-item-url" value="/catalog/desert/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/desert/14_slad.jpg"></div>
			<h3>Манго-маракуйя</h3>
			<p></br><b class="veskal">150 г., 230 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>220 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
	<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 1 -->
<!-- ДЕСЕРТЫ -->


<!-- Block 1 -->
<div class="Products">
<div class="Title" name="2">

<h1>РОЛЛЫ СЛАДКИЕ</h1>
	<ul><li><a href="#2"></a></li>
	<li><a href="#1">десерты</a></li>
		
	</ul>
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_1_slad">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_slad" />
			<input type="hidden" name="my-item-name" value="Венеция" />
			<input type="hidden" name="my-item-price" value="265" />
			<input type="hidden" name="my-item-url" value="/catalog/rolls/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/rolls/1_slad.jpg"></div>
			<h3>Венеция</h3>
			<p>Банан, кокосовая стружка, манго, шоколадная стружка + соус на выбор.</br><b class="veskal">200 г., 273 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>265 р.</b></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_2_slad">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_slad" />
			<input type="hidden" name="my-item-name" value="Марсель" />
			<input type="hidden" name="my-item-price" value="265" />
			<input type="hidden" name="my-item-url" value="/catalog/rolls/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/rolls/2_slad.jpg"></div>
			<h3>Марсель</h3>
			<p>Киви, клубника, манго, кокосовая стружка + соус на выбор.</br><b class="veskal">200 г., 265 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>265 р.</b></span>		
		</form><dd class="newhit"></dd>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_3_slad">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_slad" />
			<input type="hidden" name="my-item-name" value="Барселона" />
			<input type="hidden" name="my-item-price" value="265" />
			<input type="hidden" name="my-item-url" value="/catalog/rolls/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/rolls/3_slad.jpg"></div>
			<h3>Барселона</h3>
			<p>Киви, клубника, манго, шоколадная стружка + соус на выбор.</br><b class="veskal">200 г., 267 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>265 р.</b></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_4_slad">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_slad" />
			<input type="hidden" name="my-item-name" value="Милан" />
			<input type="hidden" name="my-item-price" value="265" />
			<input type="hidden" name="my-item-url" value="/catalog/rolls/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/rolls/4_slad.jpg"></div>
			<h3>Милан</h3>
			<p>Сыр маскарпоне, киви, банан + соус на выбор.</br><b class="veskal">200 г., 260 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>265 р.</b></span>		
		</form><dd class="newhit"></dd>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_5_slad">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_slad" />
			<input type="hidden" name="my-item-name" value="Женева" />
			<input type="hidden" name="my-item-price" value="265" />
			<input type="hidden" name="my-item-url" value="/catalog/rolls/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/rolls/5_slad.jpg"></div>
			<h3>Женева</h3>
			<p>Блин, сыр маскарпоне, клубника, киви, банан + соус на выбор.</br><b class="veskal">200 г., 270 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>265 р.</b></span>		
		</form><dd class="newhit1"></dd>
	</li>
	<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 1 -->
