<!-- САШИМИ -->

<!-- Block 1 -->
<div class="Products">
<div class="Title" name="1">
	<h1>САШИМИ</h1>
	
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_1_sah">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_sah" />
			<input type="hidden" name="my-item-name" value="Креветка" />
			<input type="hidden" name="my-item-price" value="230" />
			<input type="hidden" name="my-item-url" value="/catalog/sash/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/sash/1_sah.jpg"></div>
			<h3>Креветка</h3>
			<p>Креветка, чука, имбирь, лимон.</br></br><b class="veskal">60/30/15/10 г., 150 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>230 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_sah">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_sah" />
			<input type="hidden" name="my-item-name" value="Лосось" />
			<input type="hidden" name="my-item-price" value="230" />
			<input type="hidden" name="my-item-url" value="/catalog/sash/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/sash/2_sah.jpg"></div>
			<h3>Лосось</h3>
			<p>Норвежский лосось, чука, имбирь, лимон.</br><b class="veskal">60/30/15/10 г., 110 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>230 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_3_sah">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_sah" />
			<input type="hidden" name="my-item-name" value="Угорь" />
			<input type="hidden" name="my-item-price" value="230" />
			<input type="hidden" name="my-item-url" value="/catalog/sash/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/sash/3_sah.jpg"></div>
			<h3>Угорь</h3>
			<p>Копчёный угорь, чука, имбирь, лимон.</br><b class="veskal">60/30/15/10 г., 141 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>230 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_sah">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_sah" />
			<input type="hidden" name="my-item-name" value="Тунец" />
			<input type="hidden" name="my-item-price" value="230" />
			<input type="hidden" name="my-item-url" value="/catalog/sash/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/sash/4_sah.jpg"></div>
			<h3>Тунец</h3>
			<p>Тунец, чука, имбирь, лимон.</br></br><b class="veskal">60/30/15/10 г., 101 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>230 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_5_sah">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_sah" />
			<input type="hidden" name="my-item-name" value="Ассорти" />
			<input type="hidden" name="my-item-price" value="900" />
			<input type="hidden" name="my-item-url" value="/catalog/sash/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/sash/5_sah.jpg"></div>
			<h3>Ассорти</h3>
			<p>Тигровая креветка, копчёный угорь, тунец, лосось, чука, имбирь, лимон.</br><b class="veskal">240/60/30/20 г., 500 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>900 р.</b></span>		
		</form>
	</li>
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 1 -->
