<!-- ГОРЯЧЕЕ 
<li><a href="#1">горячее</a></li>
<li><a href="#2">супы</a></li>
<li><a href="#3">шашлычки</a></li>

--><img src="/catalog/wok/osnova.jpg"><div class="Products">
<div class="Title" name="1">
<div class="commbl2"><nobr>Выберите основу и скажите её номер оператору.</nobr></div>
	<h1>BIG-WOK</h1>
	<ul>
		
	</ul>
	
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_6_wok">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="6_wok" />
			<input type="hidden" name="my-item-name" value="C курицей в соусе Хой-син" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/wok/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img id="hkard" <img src="/catalog/wok/6_wok.jpg"></div>
			<h3 id="wz">C курицей по-китайски</br> в соусе Хой-син</h3>
			<p id="pwok"></br>лук, перец болг., морковь, китай-</br>ская капуста, курица, курин. бульон, соус рыбный,</br> соус хой-син</p>
			<p></br></br><b class="veskal3"></b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>285 р.</b></span>		
		</form><dd class="newhitwok1"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_wok">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_wok" />
			<input type="hidden" name="my-item-name" value="C овощами" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/wok/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img id="hkard" <img src="/catalog/wok/2_wok.jpg"></div>
			<h3 id="wz">C овощами</h3>
			<p id="pwok">лук, перец болг., морковь, китай-</br>ская капуста, чеснок, курин. бульон. </br></p>
			<p></br></br><b class="veskal3"></b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>285 р.</b></span>		
		</form><dd class="newhitwok1"></dd>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_8_wok">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="8_wok" />
			<input type="hidden" name="my-item-name" value="Лапша карбонара" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/wok/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img id="hkard" <img src="/catalog/wok/8_wok.jpg"></div>
			<h3 id="wz">Лапша карбонара</h3>
			<p id="pwok">Чеснок, перец болг., бекон, сливки, острый соус табаско, </br>сыр пармезан, яйцо. </br></p>
			<p></br></br><b class="veskal3"></b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>285 р.</b></span>		
		</form><dd class="newhitwok"></dd>
	</li>
	
			<li>
		<form method="post" action="" class="jcart" id="Item_4_wok">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_wok" />
			<input type="hidden" name="my-item-name" value="С лососем в сливочном соусе" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/wok/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img id="hkard" <img src="/catalog/wok/4_wok.jpg"></div>
			<h3 id="wz">С лососем в сливочном соусе</h3>
			<p id="pwok"></br>лук, перец болг., лосось, соус устричный, соус сливочный, китайский салат. </br>сыр пармезан,</br> яйцо. </br></p>
			<p></br></br><b class="veskal3"></b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>285 р.</b></span>		
		</form><dd class="newhitwok1"></dd>
	</li>
			<li>
		<form method="post" action="" class="jcart" id="Item_5_wok">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_wok" />
			<input type="hidden" name="my-item-name" value="С морепродуктами" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/wok/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img id="hkard" <img src="/catalog/wok/5_wok.jpg"></div>
			<h3 id="wz">С морепродуктами</h3>
			<p id="pwok">Лосось, мидии, креветка, чеснок, лук, перец болг., сливоч. соус, соус киккоман, лимон. сок, базилик,</br> кунжут. </br></p>
			<p></br></br><b class="veskal3"></b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>285 р.</b></span>		
		</form><dd class="newhitwok1"></dd>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_1_wok">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_wok" />
			<input type="hidden" name="my-item-name" value="С курицей в соусе карри" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/wok/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img id="hkard" <img src="/catalog/wok/1_wok.jpg"></div>
			<h3 id="wz">С курицей в соусе карри</h3>
			<p id="pwok">Курица, кокосовое молоко, лук, перец болг., морковь, китайская капуста, бульон куриный, соус карри, перец острый, кунжут. </br></br></p>
			<p></br></br><b class="veskal3"></b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>285 р.</b></span>		
		</form><dd class="newhitwok1"></dd>
	</li>
			<li>
		<form method="post" action="" class="jcart" id="Item_7_wok">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="7_wok" />
			<input type="hidden" name="my-item-name" value="Со свининой в тамариндовом соусе" />
			<input type="hidden" name="my-item-price" value="285" />
			<input type="hidden" name="my-item-url" value="/catalog/wok/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img id="hkard" <img src="/catalog/wok/7_wok.jpg"></div>
			<h3 id="wz">Со свининой в </br>тамариндовом соусе</h3>
			<p id="pwok"></br>лук, перец болг., морковь, капуста китайск., курин. бульон, свинина, соус тамриндовый,</br> яйцо, кунжут. </br></p>
			<p></br></br><b class="veskal3"></b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>285 р.</b></span>		
		</form><dd class="newhitwok1"></dd>
	</li>
			<li>
		<form method="post" action="" class="jcart" id="Item_3_wok">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_wok" />
			<input type="hidden" name="my-item-name" value="С говядиной в устричном соусе" />
			<input type="hidden" name="my-item-price" value="285" />

			<input type="hidden" name="my-item-url" value="/catalog/wok/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img id="hkard" <img src="/catalog/wok/3_wok.jpg"></div>
			<h3 id="wz">С говядиной в устричном соусе</h3>
			<p id="pwok"></br>говядина, лук, морковь, перц болг., соус устричный, капуста</br> китайская,</br> аджиномото. </br></p>
			<p></br></br><b class="veskal3"></b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>285 р.</b></span>		
		</form><dd class="newhitwok1"></dd>
	</li>

<li>
		<form method="post" action="" class="jcart" id="Item_10_wok">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="10_wok" />
			<input type="hidden" name="my-item-name" value="Рис с обжаренными овощами" />
			<input type="hidden" name="my-item-price" value="285" />

			<input type="hidden" name="my-item-url" value="/catalog/wok/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img id="hkard" <img src="/catalog/wok/10_wok.jpg"></div>
			<h3 id="wz">Рис с обжаренными овощами</h3>
			<p id="pwok"></br>рис Гохан, грибы, морковь, горошек, лук.</br>  </br></p>
			<p></br></br><b class="veskal3"></b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>285 р.</b></span>		
		</form><dd class="newhitwok1"></dd>
	</li>
<li>
		<form method="post" action="" class="jcart" id="Item_9_wok">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="9_wok" />
			<input type="hidden" name="my-item-name" value="Рис с обжаренными морепродуктами" />
			<input type="hidden" name="my-item-price" value="285" />

			<input type="hidden" name="my-item-url" value="/catalog/wok/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img id="hkard" <img src="/catalog/wok/9_wok.jpg"></div>
			<h3 id="wz">Рис с обжаренными морепродуктами</h3>
			<p id="pwok"></br>рис Гохан, лосось, креветка, окунь, гребешок.</br>  </br></p>
			<p></br></br><b class="veskal3"></b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>285 р.</b></span>		
		</form><dd class="newhitwok1"></dd>
	</li>
	
	
	

	
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 2 -->
