<!-- ГОРЯЧЕЕ 
<li><a href="#1">горячее</a></li>
<li><a href="#2">супы</a></li>
<li><a href="#3">шашлычки</a></li>

--><div class="Products">
<div class="Title" name="1">
	<h1>Колбаски</h1>
	<ul>
		<li><a href="#2">горячие блюда</a></li>
		<li><a href="#3">супы</a></li>
	</ul>
	
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_1_sar">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_sar" />
			<input type="hidden" name="my-item-name" value="Гамбургские" />
			<input type="hidden" name="my-item-price" value="275" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/1_sar.jpg"></div>
			<h3>Гамбургские</h3>
			<p>(свинина, специи + гарнир на выбор)</br><b class="veskal">100 гр.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>275 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_sar">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_sar" />
			<input type="hidden" name="my-item-name" value="Эдинбургские" />
			<input type="hidden" name="my-item-price" value="275" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/2_sar.jpg"></div>
			<h3>Эдинбургские</h3>
			<p>(говядина, специи + гарнир на выбор)</br><b class="veskal">100 гр.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>275 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_3_sar">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_sar" />
			<input type="hidden" name="my-item-name" value="Пражские" />
			<input type="hidden" name="my-item-price" value="275" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/3_sar.jpg"></div>
			<h3>Пражские</h3>
			<p>(баранина, специи + гарнир на выбор)</br><b class="veskal">100 гр.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>275 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_sar">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_sar" />
			<input type="hidden" name="my-item-name" value="Бременские" />
			<input type="hidden" name="my-item-price" value="275" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/4_sar.jpg"></div>
			<h3>Бременские</h3>
			<p>(курица, специи + гарнир на выбор)</br><b class="veskal">100 гр.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>275 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_5_sar">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_sar" />
			<input type="hidden" name="my-item-name" value="Мюнхенские" />
			<input type="hidden" name="my-item-price" value="275" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/5_sar.jpg"></div>
			<h3>Мюнхенские</h3>
			<p>(говядина, свинина, специи + гарнир на выбор)</br><b class="veskal">100 гр.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>275 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_6_sar">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="6_sar" />
			<input type="hidden" name="my-item-name" value="Пармские" />
			<input type="hidden" name="my-item-price" value="275" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/6_sar.jpg"></div>
			<h3>Пармские</h3>
			<p>(свинина, говядина, специи + гарнир на выбор)</br><b class="veskal">100 гр.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>275 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_7_sar">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="7_sar" />
			<input type="hidden" name="my-item-name" value="Ассорти" />
			<input type="hidden" name="my-item-price" value="1500" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/7_sar.jpg"></div>
			<h3>Ассорти</h3>
			<p>(ассорти колбасок + гарнир на выбор)</br><b class="veskal">600 гр./600 гр.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>1500 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
	
	
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 2 -->

<div class="Products">
<div class="Title" name="1">
	<h1>ШАШЛЫЧКИ</h1>
	<ul>
		<li><a href="#2">горячие блюда</a></li>
		<li><a href="#3">супы</a></li>
	</ul>
	
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_19_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000288" />
			<input type="hidden" name="my-item-name" value="Угорь в беконе" />
			<input type="hidden" name="my-item-price" value="185" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/19_gor.jpg"></div>
			<h3>Угорь в беконе</h3>
			<p>(угорь, бекон, болгарский перец)</br><b class="veskal">4 шт./80 гр.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>185 р.</b></span>		
		</form><dd class="newhit4"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_20_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000289" />
			<input type="hidden" name="my-item-name" value="Мидии в беконе" />
			<input type="hidden" name="my-item-price" value="185" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/20_gor.jpg"></div>
			<h3>Мидии в беконе</h3>
			<p></br></br><b class="veskal">4 шт./100 гр.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>185 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_21_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000290" />
			<input type="hidden" name="my-item-name" value="Лосось" />
			<input type="hidden" name="my-item-price" value="185" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/21_gor.jpg"></div>
			<h3>Лосось</h3>
			<p></br></br><b class="veskal">4 шт./60 гр.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>185 р.</b></span>		
		</form><dd class="newhit4"></dd>
	</li>
	
	<li>
		<form method="post" action="" class="jcart" id="Item_22_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000291" />
			<input type="hidden" name="my-item-name" value="Креветка" />
			<input type="hidden" name="my-item-price" value="185" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/22_gor.jpg"></div>
			<h3>Креветка</h3>
			<p>(креветка, лук порей)</br></br><b class="veskal">3 шт./50 гр.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>185 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_23_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000292" />
			<input type="hidden" name="my-item-name" value="Гребешок" />
			<input type="hidden" name="my-item-price" value="185" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/23_gor.jpg"></div>
			<h3>Гребешок</h3>
			<p></br></br><b class="veskal">4 шт./60 гр.</b></p>

			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>185 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>	
	<li>
		<form method="post" action="" class="jcart" id="Item_24_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="100000293" />
			<input type="hidden" name="my-item-name" value="Ассорти" />
			<input type="hidden" name="my-item-price" value="850" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/24_gor.jpg"></div>
			<h3>Ассорти</h3>
			<p>(Лосось, гребешок, угорь в беконе, мидии в беконе, креветка)</br><b class="veskal"></b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>850 р.</b></span>		
		</form>
	</li>
	
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 2 -->

<!-- Block 1 -->
<div class="Products">
<div class="Title" name="2">
	<h1>ГОРЯЧИЕ БЛЮДА</h1>
	<ul>
	<li><a href="#3">супы</a></li>
	<li><a href="#1">шашлычки</a></li>
	</ul>
</div>
<!-- ITEMS -->
<ul class="Items">
<li>
		<form method="post" action="" class="jcart" id="Item_1_nag">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_nag" />
			<input type="hidden" name="my-item-name" value="Нагетсы" />
			<input type="hidden" name="my-item-price" value="250" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/1_nag.jpg"></div>
			<h3>Нагетсы куриные</h3>
			<p><b class="veskal">220 г.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>250 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
<li>
		<form method="post" action="" class="jcart" id="Item_rul">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="rul" />
			<input type="hidden" name="my-item-name" value="Рулет "Техас"" />
			<input type="hidden" name="my-item-price" value="300" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/rul.jpg"></div>
			<h3>Рулет "Техас"</h3>
			<p>(курица, фасоль, морковь, панировка)<b class="veskal">220 г.</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>300 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_1_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_gor" />
			<input type="hidden" name="my-item-name" value="Крылышки Баффало" />
			<input type="hidden" name="my-item-price" value="250" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/1_gor.jpg"></div>
			<h3>Крылышки Баффало</h3>
			<p><b class="veskal">500 г. + соус</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>250 р.</b></span>		
		</form><dd class="newhit4"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_gor" />
			<input type="hidden" name="my-item-name" value="Картофель по-деревенски" />
			<input type="hidden" name="my-item-price" value="120" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/2_gor.jpg"></div>
			<h3>Картофель по-деревенски</h3>
			<p></br></br><b class="veskal">300 г. + соус</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>120 р.</b></span>		
		</form><dd class="newhit5"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_3_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_gor" />
			<input type="hidden" name="my-item-name" value="Картофель фри" />
			<input type="hidden" name="my-item-price" value="100" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/3_gor.jpg"></div>
			<h3>Картофель фри</h3>
			<p><b class="veskal">300 г. + соус</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>100 р.</b></span>		
		</form><dd class="newhit5"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_gor" />
			<input type="hidden" name="my-item-name" value="Креветки королевские в кляре" />
			<input type="hidden" name="my-item-price" value="250" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/4_gor.jpg"></div>
			<h3>Креветки королевские в кляре и панировке</h3>
			<p></br></br><b class="veskal">7 шт. + соус</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>250 р.</b></span>		
		</form><dd class="newhit4"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_5_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_gor" />
			<input type="hidden" name="my-item-name" value="Гёдза с креветками" />
			<input type="hidden" name="my-item-price" value="250" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/5_gor.jpg"></div>
			<h3>Гёдза с креветками</h3>
			<p><b class="veskal">7 шт. + соус</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>250 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_6_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="6_gor" />
			<input type="hidden" name="my-item-name" value="Гёдза с мясом" />
			<input type="hidden" name="my-item-price" value="250" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/6_gor.jpg"></div>
			<h3>Гёдза с мясом</h3>
			<p><b class="veskal">7 шт. + соус</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>250 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_10_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="10_gor" />
			<input type="hidden" name="my-item-name" value="Лягушачьи лапки" />
			<input type="hidden" name="my-item-price" value="250" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/10_gor.jpg"></div>
			<h3>Лягушачьи лапки</h3>
			<p></br><b class="veskal">300г. + соус</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>250 р.</b></span>		
		</form><dd class="newhit1"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_11_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="11_gor" />
			<input type="hidden" name="my-item-name" value="Лягушачьи лапки в кляре" />
			<input type="hidden" name="my-item-price" value="250" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/11_gor.jpg"></div>
			<h3>Лягушачьи лапки в кляре</h3>
			<p></br><b class="veskal">300г. + соус</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>250 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_12_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="12_gor" />
			<input type="hidden" name="my-item-name" value="Палочки из сыра Моцарела" />
			<input type="hidden" name="my-item-price" value="300" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/12_gor.jpg"></div>
			<h3>Палочки из сыра Моцарела</h3>
			<p></br></br><b class="veskal">8 шт. + соус</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>300 р.</b></span>		
		</form><dd class="newhit6"></dd>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_18_gor">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="18_gor" />
			<input type="hidden" name="my-item-name" value="Кольца кальмара" />
			<input type="hidden" name="my-item-price" value="250" />
			<input type="hidden" name="my-item-url" value="/catalog/gor/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/gor/18_gor.jpg"></div>
			<h3>Кольца кальмара</h3>
			<p></br><b class="veskal">10 шт. + соус</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>250 р.</b></span>		
		</form>
	</li>	

	
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 1 -->

<!-- Block 2 -->
<div class="Products">
<div class="Title" name="3">
	<h1>СУПЫ</h1>
	<ul>
<li><a href="#1">шашлычки</a></li>
<li><a href="#2">горячее</a></li>

	</ul>
</div>
<!-- ITEMS -->
<ul class="Items">
<li>
	<form method="post" action="" class="jcart" id="Item_13_gor">
		<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
		<input type="hidden" name="my-item-id" value="13_gor" />
		<input type="hidden" name="my-item-name" value="Мисо суп" />
		<input type="hidden" name="my-item-price" value="100" />
		<input type="hidden" name="my-item-url" value="/catalog/gor/" />
		<input class="qty" type="text" name="my-item-qty" value="1"/>
		<div><img src="/catalog/gor/13_gor.jpg"></div>
		<h3>Мисо суп</h3>
		<p>Тофу, грибы намэко, кунжут, мисо паста, морские водоросли, зелёный лук.</br><b class="veskal">400 г.</b></p>
		<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>100 р.</b></span>		
	</form><dd class="newhit5"></dd>
</li><li>
	<form method="post" action="" class="jcart" id="Item_14_gor">
		<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
		<input type="hidden" name="my-item-id" value="14_gor" />
		<input type="hidden" name="my-item-name" value="Суп с лососем" />
		<input type="hidden" name="my-item-price" value="110" />
		<input type="hidden" name="my-item-url" value="/catalog/gor/" />
		<input class="qty" type="text" name="my-item-qty" value="1"/>
		<div><img src="/catalog/gor/14_gor.jpg"></div>
		<h3>Суп с лососем</h3>
		<p>Лосось, салат айсберг, грибы шампиньоны, соевый соус, зелёный лук, кунжут.</br><b class="veskal">425 г.</b></p>
		<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>110 р.</b></span>		
	</form>
</li>	<li>
	<form method="post" action="" class="jcart" id="Item_15_gor">
		<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
		<input type="hidden" name="my-item-id" value="15_gor" />
		<input type="hidden" name="my-item-name" value="Суп эби удон" />
		<input type="hidden" name="my-item-price" value="200" />
		<input type="hidden" name="my-item-url" value="/catalog/gor/" />
		<input class="qty" type="text" name="my-item-qty" value="1"/>
		<div><img src="/catalog/gor/15_gor.jpg"></div>
		<h3>Суп эби удон</h3>
		<p>Лапша удон, бульон суимоно, крабовое мясо, креветка, шампиньоны, яйцо, зелёный лук.</br><b class="veskal">450 г.</b></p>
		<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>200 р.</b></span>		
	</form>
</li>	<li>
	<form method="post" action="" class="jcart" id="Item_16_gor">
		<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
		<input type="hidden" name="my-item-id" value="16_gor" />
		<input type="hidden" name="my-item-name" value="Тайский суп" />
		<input type="hidden" name="my-item-price" value="190" />
		<input type="hidden" name="my-item-url" value="/catalog/gor/" />
		<input class="qty" type="text" name="my-item-qty" value="1"/>
		<div><img src="/catalog/gor/16_gor.jpg"></div>
		<h3>Тайский суп</h3>
		<p>Кокосовое молоко, креветка, грибы шампиньоны, специи томкха, сухарики.</br><b class="veskal">440 г.</b></p>
		<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>190 р.</b></span>		
	</form>
</li>	<li>
	<form method="post" action="" class="jcart" id="Item_17_gor">
		<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
		<input type="hidden" name="my-item-id" value="17_gor" />
		<input type="hidden" name="my-item-name" value="Суп суимоно" />
		<input type="hidden" name="my-item-price" value="150" />
		<input type="hidden" name="my-item-url" value="/catalog/gor/" />
		<input class="qty" type="text" name="my-item-qty" value="1"/>
		<div><img src="/catalog/gor/17_gor.jpg"></div>
		<h3>Суп суимоно</h3>
		<p>Бульон суимоно, морепродукты, рис, кунжут.</br><b class="veskal">430 г.</b></p>
		<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>150 р.</b></span>		
	</form>
</li>		
	
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 2 -->
