<!-- Block 1 -->
<div class="Products">
<div class="Title" name="1">
	<h2>ПИЦЦА</h2>
	<ul>
		
		<li><a href="#4">вниз меню</a></li>
	</ul>
</div>
<!-- ITEMS <div class="newhit"><img src="/catalog/pizza/newhit.png"></div>		-->
<ul class="Items Pizza">
	<li>
		<form method="post" action="" class="jcart" id="Item_22_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="22_p45" />
			<input type="hidden" name="my-item-name" value="Столичная 45" />
			<input type="hidden" name="my-item-price" value="690" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/22_p45.jpg"></div>
			<h3>Столичная</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр дорблю, ветчина, колбаса пепперони, перец болгарский, огурцы маринованные.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/1000 г./</b><b class="pizzapricered">540 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1700 г./</b><b class="pizzapricered">690 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_22_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="22_p33" />
			<input type="hidden" name="my-item-name" value="Столичная 33" />
			<input type="hidden" name="my-item-price" value="540" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit1"></dd>
	</li>
	
		</li><li>
		<form method="post" action="" class="jcart" id="Item_23_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="23_p45" />
			<input type="hidden" name="my-item-name" value="Кальцоне большая" />
			<input type="hidden" name="my-item-price" value="610" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/23_p45.jpg"></div>
			<h3>Кальцоне</h3>
			<p>Соус "el'Grande", сыр моццарелла, шампиньоны, ветчина, огурцы маринованные, колбаса пепперони, томаты.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">СТД.</b>/830 г./</b><b class="pizzapricered">470 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">БОЛ.</b>/1350 г./</b><b class="pizzapricered">610 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart12"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_23_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="23_p33" />
			<input type="hidden" name="my-item-name" value="Кальцоне стандартная" />
			<input type="hidden" name="my-item-price" value="470" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart11"/></span>		
		</form><dd class="newhit1"></dd>
	</li>
		</li><li>
		<form method="post" action="" class="jcart" id="Item_24_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="24_p45" />
			<input type="hidden" name="my-item-name" value="Закрытая с мясом 45" />
			<input type="hidden" name="my-item-price" value="710" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/24_p45.jpg"></div>
			<h3>Закрытая с мясом</h3>
			<p>Соус "el'Grande", сыр моццарелла, ветчина, бекон, колбаса пепперони, шампиньоны, перец.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/1270 г./</b><b class="pizzapricered">580 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1860 г./</b><b class="pizzapricered">710 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_24_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="24_p33" />
			<input type="hidden" name="my-item-name" value="Закрытая с мясом 33" />
			<input type="hidden" name="my-item-price" value="580" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit1"></dd>
	</li>
		</li>
		</li><li>
		<form method="post" action="" class="jcart" id="Item_25_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="25_p45" />
			<input type="hidden" name="my-item-name" value="Закрытая с рыбой 45" />
			<input type="hidden" name="my-item-price" value="760" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/25_p45.jpg"></div>
			<h3>Закрытая с рыбой</h3>
			<p>Соус "Тар-Тар", сыр моццарелла, лосось, окунь, лук порей.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/945 г./</b><b class="pizzapricered">610 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1720 г./</b><b class="pizzapricered">760 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_25_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="25_p33" />
			<input type="hidden" name="my-item-name" value="Закрытая с рыбой 33" />
			<input type="hidden" name="my-item-price" value="610" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit1"></dd>
	</li>
	</li>
		</li><li>
		<form method="post" action="" class="jcart" id="Item_26_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="26_p45" />
			<input type="hidden" name="my-item-name" value="Тутти-Фрутти 45" />
			<input type="hidden" name="my-item-price" value="620" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/26_p45.jpg"></div>
			<h3>Тутти-Фрутти</h3>
			<p>Соус сливочный, сыр маскарпоне, киви, клубника, банан, ананас.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/750 г./</b><b class="pizzapricered">470 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1300 г./</b><b class="pizzapricered">620 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_26_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="26_p33" />
			<input type="hidden" name="my-item-name" value="Тутти-Фрутти 33" />
			<input type="hidden" name="my-item-price" value="470" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit1"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_1_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_p45" />
			<input type="hidden" name="my-item-name" value="Маргарита 45" />
			<input type="hidden" name="my-item-price" value="460" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/1_p45.jpg"></div>
			<h3>Маргарита</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр пармезан,  помидоры, базилик.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/700 г./</b><b class="pizzapricered">380 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1250 г./</b><b class="pizzapricered">460 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>
			
		</form>

		<form method="post" action="" class="jcart" id="Item_1_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_p33" />
			<input type="hidden" name="my-item-name" value="Маргарита 33" />
			<input type="hidden" name="my-item-price" value="380" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>
					
		</form><dd class="newhit6"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_p45" />
			<input type="hidden" name="my-item-name" value="Гавайская 45" />
			<input type="hidden" name="my-item-price" value="540" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/2_p45.jpg"></div>
			<h3>Гавайская</h3>
			<p>Соус "el'Grande", сыр моццарелла, ветчина, ананасы, перец болгарский.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/850 г./</b><b class="pizzapricered">430 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1500 г./</b><b class="pizzapricered">540 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_2_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_p33" />
			<input type="hidden" name="my-item-name" value="Гавайская 33" />
			<input type="hidden" name="my-item-price" value="430" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_3_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_p45" />
			<input type="hidden" name="my-item-name" value="4 сыра 45" />
			<input type="hidden" name="my-item-price" value="610" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/3_p45.jpg"></div>
			<h3>4 сыра</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр пармезан, сыр дор блю, сыр швейцарский, тимьян.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/650 г./</b><b class="pizzapricered">450 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1150 г./</b><b class="pizzapricered">610 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_3_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_p33" />
			<input type="hidden" name="my-item-name" value="4 сыра 33" />
			<input type="hidden" name="my-item-price" value="450" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit6"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_p45" />
			<input type="hidden" name="my-item-name" value="Грибная 45" />
			<input type="hidden" name="my-item-price" value="540" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/4_p45.jpg"></div>
			<h3>Грибная</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр чеддер копчёный, шампиньоны свежие и маринованные, маслины.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/650 г./</b><b class="pizzapricered">440 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1150 г./</b><b class="pizzapricered">540 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_4_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_p33" />
			<input type="hidden" name="my-item-name" value="Грибная 33" />
			<input type="hidden" name="my-item-price" value="440" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit6"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_5_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_p45" />
			<input type="hidden" name="my-item-name" value="Вегетарианская 45" />
			<input type="hidden" name="my-item-price" value="580" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/5_p45.jpg"></div>
			<h3>Вегетарианская</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр пармезан, шампиньоны свежие и маринованные, маслины, помидоры, перец болгарский, баклажаны, картофель фри.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/950 г./</b><b class="pizzapricered">440 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1540 г./</b><b class="pizzapricered">580 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form><dd class="newhit6"></dd>

		<form method="post" action="" class="jcart" id="Item_5_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_p33" />
			<input type="hidden" name="my-item-name" value="Вегетарианская 33" />
			<input type="hidden" name="my-item-price" value="440" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_6_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="6_p45" />
			<input type="hidden" name="my-item-name" value="Венская 45" />
			<input type="hidden" name="my-item-price" value="580" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/6_p45.jpg"></div>
			<h3>Венская</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр швейцарский, сыр пармезан, сосиски венские отборные.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/750 г./</b><b class="pizzapricered">450 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1250 г./</b><b class="pizzapricered">580 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_6_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="6_p33" />
			<input type="hidden" name="my-item-name" value="Венская 33" />
			<input type="hidden" name="my-item-price" value="450" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit1"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_7_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="7_p45" />
			<input type="hidden" name="my-item-name" value="Тропикана 45" />
			<input type="hidden" name="my-item-price" value="610" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/7_p45.jpg"></div>
			<h3>Тропикана</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр чеддер копчёный, филе курицы, ананасы, базилик.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/750 г./</b><b class="pizzapricered">470 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1400 г./</b><b class="pizzapricered">610 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_7_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="7_p33" />
			<input type="hidden" name="my-item-name" value="Тропикана 33" />
			<input type="hidden" name="my-item-price" value="470" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_8_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="8_p45" />
			<input type="hidden" name="my-item-name" value="Пепперони 45" />
			<input type="hidden" name="my-item-price" value="620" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/8_p45.jpg"></div>
			<h3>Пепперони</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр пармезан, колбаса пепперони, шампиньоны маринованные, базилик, орегано.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/750 г./</b><b class="pizzapricered">480 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1300 г./</b><b class="pizzapricered">620 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_8_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="8_p33" />
			<input type="hidden" name="my-item-name" value="Пепперони 33" />
			<input type="hidden" name="my-item-price" value="480" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_9_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="9_p45" />
			<input type="hidden" name="my-item-name" value="Времена года 45" />
			<input type="hidden" name="my-item-price" value="610" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/9_p45.jpg"></div>
			<h3>Времена года</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр памезан, ветчина, колбаса пепперони, шампиньоны маринованные, мидии, помидоры, маслины.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/900 г./</b><b class="pizzapricered">480 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1550 г./</b><b class="pizzapricered">610 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_9_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="9_p33" />
			<input type="hidden" name="my-item-name" value="Времена года 33" />
			<input type="hidden" name="my-item-price" value="480" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit"></dd>
	</li>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_10_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="10_p45" />
			<input type="hidden" name="my-item-name" value="Деревенская 45" />
			<input type="hidden" name="my-item-price" value="660" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/10_p45.jpg"></div>
			<h3>Деревенская</h3>
			<p>Соус "el'Grande", сыр моццарелла, бекон, ветчина, шампиньоны маринованные, огурцы маринованные, помидоры, базилик.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/1000 г./</b><b class="pizzapricered">530 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1700 г./</b><b class="pizzapricered">660 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_10_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="10_p33" />
			<input type="hidden" name="my-item-name" value="Деревенская 33" />
			<input type="hidden" name="my-item-price" value="530" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form>
	</li>
		</li>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_11_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="11_p45" />
			<input type="hidden" name="my-item-name" value="Мексиканская 45" />
			<input type="hidden" name="my-item-price" value="650" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/11_p45.jpg"></div>
			<h3>Мексиканская</h3>
			<p>Соус "el'Grande", сыры моццарел-ла и пармезан, говядина, колбаса пепперони, фасоль красн., шам-пиньоны маринован., острые пер-чики хлапенью, орегано, маслины.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/850 г./</b><b class="pizzapricered">510 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1550 г./</b><b class="pizzapricered">650 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_11_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="11_p33" />
			<input type="hidden" name="my-item-name" value="Мексиканская 33" />
			<input type="hidden" name="my-item-price" value="510" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form>
	</li>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_12_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="12_p45" />
			<input type="hidden" name="my-item-name" value="Суприм 45" />
			<input type="hidden" name="my-item-price" value="660" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/12_p45.jpg"></div>
			<h3>Суприм</h3>
			<p>Соус "el'Grande", сыр моццарелла, буженина, колбаса пепперони, шампиньоны маринованные, перец болгарский, орегано.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/900 г./</b><b class="pizzapricered">530 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1750 г./</b><b class="pizzapricered">660 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_12_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="12_p33" />
			<input type="hidden" name="my-item-name" value="Суприм 33" />
			<input type="hidden" name="my-item-price" value="530" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form>
	</li>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_13_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="13_p45" />
			<input type="hidden" name="my-item-name" value="Оригинальная 45" />
			<input type="hidden" name="my-item-price" value="660" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/13_p45.jpg"></div>
			<h3>Оригинальная</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр чеддер копчёный, говядина, буженина, колбаса пепперони, ананасы, перец болгарский, орегано.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/850 г./</b><b class="pizzapricered">520 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1600 г./</b><b class="pizzapricered">660 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_13_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="13_p33" />
			<input type="hidden" name="my-item-name" value="Оригинальная 33" />
			<input type="hidden" name="my-item-price" value="520" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form>
	</li>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_14_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="14_p45" />
			<input type="hidden" name="my-item-name" value="Морская 45" />
			<input type="hidden" name="my-item-price" value="680" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/14_p45.jpg"></div>
			<h3>Морская</h3>
			<p>Соус "el'Grande", сыр моццарелла, креветки, мидии, кальмары, осьминоги, лимонный сок, оливки.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/800 г./</b><b class="pizzapricered">530 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1450 г./</b><b class="pizzapricered">680 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_14_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="14_p33" />
			<input type="hidden" name="my-item-name" value="Морская 33" />
			<input type="hidden" name="my-item-price" value="530" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form>
	</li>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_15_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="15_p45" />
			<input type="hidden" name="my-item-name" value="Мясная 45" />
			<input type="hidden" name="my-item-price" value="690" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/15_p45.jpg"></div>
			<h3>Мясная</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр швейцарский, сыр чеддер копчёный, говядина, буженина, филе курицы, помидоры, базилик.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/900 г./</b><b class="pizzapricered">540 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1600 г./</b><b class="pizzapricered">690 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_15_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="15_p33" />
			<input type="hidden" name="my-item-name" value="Мясная 33" />
			<input type="hidden" name="my-item-price" value="540" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form>
	</li>
		</li><li>
		<form method="post" action="" class="jcart" id="Item_16_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="16_p45" />
			<input type="hidden" name="my-item-name" value="Каприз 45" />
			<input type="hidden" name="my-item-price" value="680" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/16_p45.jpg"></div>
			<h3>Каприз</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр пармезан, филе курицы, бекон, колбаса пепперони, картофель фри, помидоры, перец болгарский.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/900 г./</b><b class="pizzapricered">550 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1550 г./</b><b class="pizzapricered">680 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_16_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="16_p33" />
			<input type="hidden" name="my-item-name" value="Каприз 33" />
			<input type="hidden" name="my-item-price" value="550" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit"></dd>
	</li>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_17_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="17_p45" />
			<input type="hidden" name="my-item-name" value="Мясное изобилие 45" />
			<input type="hidden" name="my-item-price" value="700" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/17_p45.jpg"></div>
			<h3>Мясное изобилие</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр пармезан, свинина, говядина, филе курицы, колбаса пепперони, бекон, орегано.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/950 г./</b><b class="pizzapricered">550 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1600 г./</b><b class="pizzapricered">700 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_17_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="17_p33" />
			<input type="hidden" name="my-item-name" value="Мясное изобилие 33" />
			<input type="hidden" name="my-item-price" value="550" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit"></dd>
	</li>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_18_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="18_p45" />
			<input type="hidden" name="my-item-name" value="Праздничная 45" />
			<input type="hidden" name="my-item-price" value="710" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/18_p45.jpg"></div>
			<h3>Праздничная</h3>
			<p>Соус "el'Grande", сыр моццарелла, сыр швейцарский, буженина, ветчина, индейка, шампиньоны маринованные, <br>перец болгарский.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/850 г./</b><b class="pizzapricered">560 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1600 г./</b><b class="pizzapricered">710 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_18_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="18_p33" />
			<input type="hidden" name="my-item-name" value="Праздничная 33" />
			<input type="hidden" name="my-item-price" value="560" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit1"></dd>
	</li>
	</li><li>
		<form method="post" action="" class="jcart" id="Item_19_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="19_p45" />
			<input type="hidden" name="my-item-name" value="Охотничья 45" />
			<input type="hidden" name="my-item-price" value="720" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/19_p45.jpg"></div>
			<h3>Охотничья</h3>
			<p>Соус "el'Grande", сыры моццарел-ла и чеддер копч., колбаски охот-ничьи, сосиски баварские, говяди-на, помидоры, перец болгарский, маринованные огурцы, базилик.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/900 г./</b><b class="pizzapricered">560 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1600 г./</b><b class="pizzapricered">720 р .</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_19_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="19_p33" />
			<input type="hidden" name="my-item-name" value="Охотничья 33" />
			<input type="hidden" name="my-item-price" value="560" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit1"></dd>
	</li>
		</li><li>
		<form method="post" action="" class="jcart" id="Item_20_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="20_p45" />
			<input type="hidden" name="my-item-name" value="Средиземноморская 45" />
			<input type="hidden" name="my-item-price" value="810" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/20_p45.jpg"></div>
			<h3>Средиземноморская</h3>
			<p>Соус сливочный, сыр моццарелла, сыр пармезан, сыр филадельфия, тигровые креветки, норвежский лосось, лимонный сок.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/1000 г./</b><b class="pizzapricered">590 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1750 г./</b><b class="pizzapricered">810 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_20_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="20_p33" />
			<input type="hidden" name="my-item-name" value="Средиземноморская 33" />
			<input type="hidden" name="my-item-price" value="590" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit"></dd>
	</li>
	</li><li name="4">
		<form method="post" action="" class="jcart" id="Item_21_p45">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="21_p45" />
			<input type="hidden" name="my-item-name" value="эль'Гранде 45" />
			<input type="hidden" name="my-item-price" value="770" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/pizza/21_p45.jpg"></div>
			<h3>эль'Гранде</h3>
			<p>Соус "el'Grande", сыры моццарел-ла и пармезан, ветчина, говядина, колбаса пепперони, бекон, помидоры, перец болгарский, маслины, шампиньоны.
			</p>
			<b class="rv">
			<b class="pizzaprice"><b class="razmerp">33 см.</b>/1000 г./</b><b class="pizzapricered">580 р.</b><b class="sdvig">.</b><br>
			<b class="pizzaprice"><b class="razmerp">45 см.</b>/1750 г./</b><b class="pizzapricered">770 р.</b>
			</b>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart45"/></span>		
		</form>

		<form method="post" action="" class="jcart" id="Item_21_p33">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="21_p33" />
			<input type="hidden" name="my-item-name" value="эль'Гранде 33" />
			<input type="hidden" name="my-item-price" value="580" />
			<input type="hidden" name="my-item-url" value="/catalog/pizza/" />
			<input type="hidden" class="qty" type="text" name="my-item-qty" value="1"/>
		
			<span><input type="submit" name="my-add-button" value=" " class="AddCart33"/></span>		
		</form><dd class="newhit9"></dd>
	</li>
	

	
	
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 4 -->
