<meta http-equiv="content-type" content="text/html;charset=utf-8">
<!-- САЛАТЫ -->

<!-- Block 1 -->
<div class="Products">
<div class="Title" name="1">
	<h1>ДОПОЛНИТЕЛЬНЫЕ ИНГРЕДИЕНТЫ</h1>
	<ul>
		
	</ul>
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_1_dop">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_dop" />
			<input type="hidden" name="my-item-name" value="Васаби" />
			<input type="hidden" name="my-item-price" value="50" />
			<input type="hidden" name="my-item-url" value="/catalog/dop/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/dop/1_dop.jpg"></div>
			<h3>Васаби</h3>
			<p></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>50 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_dop">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_dop" />
			<input type="hidden" name="my-item-name" value="Имбирь" />
			<input type="hidden" name="my-item-price" value="50" />
			<input type="hidden" name="my-item-url" value="/catalog/dop/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/dop/2_dop.jpg"></div>
			<h3>Имбирь</h3>
			<p></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>50 р.</b></span>		
		</form>
	</li>		
	<li>
		<form method="post" action="" class="jcart" id="Item_3_dop">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_dop" />
			<input type="hidden" name="my-item-name" value="Соус соевый Кикаман" />
			<input type="hidden" name="my-item-price" value="50" />
			<input type="hidden" name="my-item-url" value="/catalog/dop/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/dop/3_dop.jpg"></div>
			<h3>Соус соевый Киккоман</h3>
			<p></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>50 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_dop">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_dop" />
			<input type="hidden" name="my-item-name" value="Соус томатный" />
			<input type="hidden" name="my-item-price" value="50" />
			<input type="hidden" name="my-item-url" value="/catalog/dop/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/dop/4_dop.jpg"></div>
			<h3>Соус томатный</h3>
			<p></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>50 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_5_dop">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_dop" />
			<input type="hidden" name="my-item-name" value="Соус спайс" />
			<input type="hidden" name="my-item-price" value="50" />
			<input type="hidden" name="my-item-url" value="/catalog/dop/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/dop/5_dop.jpg"></div>
			<h3>Соус спайс</h3>
			<p></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>50 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_6_dop">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="6_dop" />
			<input type="hidden" name="my-item-name" value="Соус коктейльный" />
			<input type="hidden" name="my-item-price" value="50" />
			<input type="hidden" name="my-item-url" value="/catalog/dop/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/dop/6_dop.jpg"></div>
			<h3>Соус коктейльный</h3>
			<p></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>50 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_7_dop">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="7_dop" />
			<input type="hidden" name="my-item-name" value="Соус ореховый" />
			<input type="hidden" name="my-item-price" value="50" />
			<input type="hidden" name="my-item-url" value="/catalog/dop/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/dop/7_dop.jpg"></div>
			<h3>Соус ореховый</h3>
			<p></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>50 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_8_dop">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="8_dop" />
			<input type="hidden" name="my-item-name" value="Соус сырно-чесночный" />
			<input type="hidden" name="my-item-price" value="50" />
			<input type="hidden" name="my-item-url" value="/catalog/dop/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/dop/8_dop.jpg"></div>
			<h3>Соус сырно-чесночный</h3>
			<p></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>50 р.</b></span>		
		</form>
	</li>
		
	<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 1 -->
