<!-- СУШИ 
<li><a href="#1">простые</a></li>
<li><a href="#2">острые</a></li>
<li><a href="#3">дунканы</a></li>
<li><a href="#4">гринканы</a></li>

-->

<!-- Block 1 -->
<div class="Products">
<div class="Title" name="1">
	<h1>СУШИ ПРОСТЫЕ</h1>
	<ul>
		<li><a href="#2">острые</a></li>
		<li><a href="#3">дунканы</a></li>
		<li><a href="#4">гринканы</a></li>
	</ul>
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_1_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_suh" />
			<input type="hidden" name="my-item-name" value="Угорь" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/1_suh.jpg"></div>
			<h3>Угорь</h3>
			<p></br><b class="veskal">30 г., 55 ккал. </b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_suh" />
			<input type="hidden" name="my-item-name" value="Тунец" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/2_suh.jpg"></div>
			<h3>Тунец</h3>
			<p></br><b class="veskal">30 г., 43 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_3_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_suh" />
			<input type="hidden" name="my-item-name" value="Креветка" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/3_suh.jpg"></div>
			<h3>Креветка</h3>
			<p></br><b class="veskal">30 г., 60 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_suh" />
			<input type="hidden" name="my-item-name" value="Лосось" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/4_suh.jpg"></div>
			<h3>Лосось</h3>
			<p></br><b class="veskal">30 г., 47 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_5_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_suh" />
			<input type="hidden" name="my-item-name" value="Лосось копчёный" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/5_suh.jpg"></div>
			<h3>Лосось копчёный</h3>
			<p></br><b class="veskal">30 г., 53 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_6_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="6_suh" />
			<input type="hidden" name="my-item-name" value="Кальмар" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/6_suh.jpg"></div>
			<h3>Кальмар</h3>
			<p></br><b class="veskal">30 г., 38 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_7_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="7_suh" />
			<input type="hidden" name="my-item-name" value="Окунь" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/7_suh.jpg"></div>
			<h3>Окунь</h3>
			<p></br><b class="veskal">30 г., 41 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_8_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="8_suh" />
			<input type="hidden" name="my-item-name" value="Осьминог" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/8_suh.jpg"></div>
			<h3>Осьминог</h3>
			<p></br><b class="veskal">30 г., 38 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_9_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="9_suh" />
			<input type="hidden" name="my-item-name" value="Тобико" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/9_suh.jpg"></div>
			<h3>Тобико</h3>
			<p></br><b class="veskal">30 г., 40 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_10_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="10_suh" />
			<input type="hidden" name="my-item-name" value="Тобико чёрный" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/10_suh.jpg"></div>
			<h3>Тобико чёрная</h3>
			<p></br><b class="veskal">30 г., 40 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_11_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="11_suh" />
			<input type="hidden" name="my-item-name" value="Икра красная" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/11_suh.jpg"></div>
			<h3>Икра красная</h3>
			<p></br><b class="veskal">32 г., 60 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_12_suh">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="12_suh" />
			<input type="hidden" name="my-item-name" value="Чука с ореховым соусом" />
			<input type="hidden" name="my-item-price" value="55" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/12_suh.jpg"></div>
			<h3>Чука с ореховым соусом</h3>
			<p></br><b class="veskal">32 г., 60 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>55 р.</b></span>		
		</form>
	</li>
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 1 -->

<!-- Block 2 -->
<div class="Products">
<div class="Title" name="2">
	<h1>СУШИ ОСТРЫЕ</h1>
	<ul>
		<li><a href="#1">простые</a></li>
		<li><a href="#3">дунканы</a></li>
		<li><a href="#4">гринканы</a></li>
	</ul>
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_1_ost">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_ost" />
			<input type="hidden" name="my-item-name" value="Угорь" />
			<input type="hidden" name="my-item-price" value="65" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/1_ost.jpg"></div>
			<h3>Угорь</h3>
			<p>Острые суши с копчёным угрём</br><b class="veskal">35 г., 70 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>65 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_ost">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_ost" />
			<input type="hidden" name="my-item-name" value="Тунец" />
			<input type="hidden" name="my-item-price" value="65" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/2_ost.jpg"></div>
			<h3>Тунец</h3>
			<p>Острые суши с тунцом</br><b class="veskal">35 г., 60 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>65 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_3_ost">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_ost" />
			<input type="hidden" name="my-item-name" value="Креветка" />
			<input type="hidden" name="my-item-price" value="65" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/3_ost.jpg"></div>
			<h3>Креветка</h3>
			<p>Острые суши с креветкой</br><b class="veskal">35 г., 79 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>65 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_ost">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_ost" />
			<input type="hidden" name="my-item-name" value="Лосось" />
			<input type="hidden" name="my-item-price" value="65" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/4_ost.jpg"></div>
			<h3>Лосось</h3>
			<p>Острые суши с норвежским лососем</br><b class="veskal">35 г., 64 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>65 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_5_ost">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_ost" />
			<input type="hidden" name="my-item-name" value="Окунь" />
			<input type="hidden" name="my-item-price" value="65" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/5_ost.jpg"></div>
			<h3>Окунь</h3>
			<p>Острые суши с окунем</br><b class="veskal">35 г., 59 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>65 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_6_ost">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="6_ost" />
			<input type="hidden" name="my-item-name" value="Грибы намэко" />
			<input type="hidden" name="my-item-price" value="65" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/6_ost.jpg"></div>
			<h3>Грибы намэко</h3>
			<p>Острые суши с грибами намэко</br><b class="veskal">35 г., 61 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>65 р.</b></span>		
		</form><dd class="newhit5"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_7_ost">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="7_ost" />
			<input type="hidden" name="my-item-name" value="Осьминог" />
			<input type="hidden" name="my-item-price" value="65" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/7_ost.jpg"></div>
			<h3>Осьминог</h3>
			<p>Острые суши с осьминогом</br><b class="veskal">35 г., 58 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>65 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
		<li>
		<form method="post" action="" class="jcart" id="Item_8_ost">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="8_ost" />
			<input type="hidden" name="my-item-name" value="Мидии" />
			<input type="hidden" name="my-item-price" value="65" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/8_ost.jpg"></div>
			<h3>Мидии</h3>
			<p>Острые суши с мидиями</br><b class="veskal">35 г., 58 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>65 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
	<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 2 -->

<!-- Block 3 -->
<div class="Products">
<div class="Title" name="3">
	<h1>ДУНКАНЫ</h1>
	<ul>
	<li><a href="#1">простые</a></li>
	<li><a href="#2">острые</a></li>
	<li><a href="#4">гринканы</a></li>
    </ul>
</div>
<!-- ITEMS -->
<ul class="Items">
<li>
		<form method="post" action="" class="jcart" id="Item_dun_rio">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="dun_rio" />
			<input type="hidden" name="my-item-name" value="Рио" />
			<input type="hidden" name="my-item-price" value="80" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/dun_rio.jpg"></div>
			<h3>Рио</h3>
			<p>Белоснежный камчатский краб 1-я фаланга, авокадо, тобико, японский майонез</br><b class="veskal">40 г., 81 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>80 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_1_dun">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_dun" />
			<input type="hidden" name="my-item-name" value="Токио" />
			<input type="hidden" name="my-item-price" value="80" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/1_dun.jpg"></div>
			<h3>Токио</h3>
			<p>Лосось, тунец, филадельфия, японский майонез</br><b class="veskal">40 г., 75 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>80 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_dun">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_dun" />
			<input type="hidden" name="my-item-name" value="Гоа" />
			<input type="hidden" name="my-item-price" value="80" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/2_dun.jpg"></div>
			<h3>Гоа</h3>
			<p>Филе индейки, огурец, икра, филадельфия, японский майонез</br><b class="veskal">40 г., 80 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>80 р.</b></span>		
		</form><dd class="newhit3"></dd>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_3_dun">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_dun" />
			<input type="hidden" name="my-item-name" value="Шанхай" />
			<input type="hidden" name="my-item-price" value="80" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/3_dun.jpg"></div>
			<h3>Шанхай</h3>
			<p>Гребешок, тобико, филадельфия, японский майонез</br><b class="veskal">40 г., 74 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>80 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_dun">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_dun" />
			<input type="hidden" name="my-item-name" value="Сеул" />
			<input type="hidden" name="my-item-price" value="80" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/4_dun.jpg"></div>
			<h3>Сеул</h3>
			<p>Коктейльная креветка, спайс, авокадо, филадельфия, японский майонез</br><b class="veskal">40 г., 83 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>80 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_5_dun">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_dun" />
			<input type="hidden" name="my-item-name" value="Сайгон" />
			<input type="hidden" name="my-item-price" value="80" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/5_dun.jpg"></div>
			<h3>Сайгон</h3>
			<p>Креветка, кальмар, филадельфия, японский майонез</br><b class="veskal">40 г., 85 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>80 р.</b></span>		
		</form><dd class="newhit4"></dd>
	</li>
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 3 -->

<!-- Block 4 -->
<div class="Products">
<div class="Title" name="4">
	<h1>ГРИНКАНЫ</h1>
	<ul>
		<li><a href="#1">простые</a></li>
		<li><a href="#2">острые</a></li>
		<li><a href="#3">дунканы</a></li>	
	</ul>
</div>
<!-- ITEMS -->
<ul class="Items">
	<li>
		<form method="post" action="" class="jcart" id="Item_1_grin">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_grin" />
			<input type="hidden" name="my-item-name" value="Тунец" />
			<input type="hidden" name="my-item-price" value="80" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/1_grin.jpg"></div>
			<h3>Тунец</h3>
			<p>Тунец, спайс, огурец</br><b class="veskal">45 г., 75 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>80 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_grin">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_grin" />
			<input type="hidden" name="my-item-name" value="Угорь" />
			<input type="hidden" name="my-item-price" value="80" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/2_grin.jpg"></div>
			<h3>Угорь</h3>
			<p>Угорь, спайс, огурец</br><b class="veskal">45 г., 87 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>80 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_3_grin">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_grin" />
			<input type="hidden" name="my-item-name" value="Креветка" />
			<input type="hidden" name="my-item-price" value="80" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/3_grin.jpg"></div>
			<h3>Креветка</h3>
			<p>Креветка, спайс, огурец</br><b class="veskal">45 г., 98 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>80 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_grin">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_grin" />
			<input type="hidden" name="my-item-name" value="Лосось" />
			<input type="hidden" name="my-item-price" value="80" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/4_grin.jpg"></div>
			<h3>Лосось</h3>
			<p>Лосось, спайс, огурец</br><b class="veskal">45 г., 81 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>80 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_5_grin">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_grin" />
			<input type="hidden" name="my-item-name" value="Краб" />
			<input type="hidden" name="my-item-price" value="80" />
			<input type="hidden" name="my-item-url" value="/catalog/susi/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/susi/5_grin.jpg"></div>
			<h3>Краб</h3>
			<p>Краб, спайс, огурец</br><b class="veskal">45 г., 81 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>80 р.</b></span>		
		</form><dd class="newhit4"></dd>
	</li>
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 4 -->
