<!-- САЛАТЫ -->

<!-- Block 1 -->
<div class="Products">
<div class="Title" name="1">
	<h1>Ассорти</h1>
	
</div>
<!-- ITEMS -->
<ul class="Items Big">
	<li>
		<form method="post" action="" class="jcart" id="Item_1_asrt">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="1_asrt" />
			<input type="hidden" name="my-item-name" value="Золотая рыбка" />
			<input type="hidden" name="my-item-price" value="500" />
			<input type="hidden" name="my-item-url" value="/catalog/asrt/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/asrt/1_asrt.jpg"></div>
			<h3>Золотая рыбка</h3>
			<p>Суши: угорь, тунец, креветка, лосось, лосось копчёный, кальмар, окунь, тобико, тобико черн., икра красная.</br><b class="veskal">302 г., 477 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>500 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_9_asrt">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="9_asrt" />
			<input type="hidden" name="my-item-name" value="Третий Рим" />
			<input type="hidden" name="my-item-price" value="900" />
			<input type="hidden" name="my-item-url" value="/catalog/asrt/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/asrt/9_asrt.jpg"></div>
			<h3>Третий Рим</h3>
			<p>Роллы: цезарь, сингапур, палермо. Суши: чука с ореховым соусом, острые мидии.</br><b class="veskal">502 г., 777 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>900 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_8_asrt">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="8_asrt" />
			<input type="hidden" name="my-item-name" value="Касабланка" />
			<input type="hidden" name="my-item-price" value="1300" />
			<input type="hidden" name="my-item-url" value="/catalog/asrt/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/asrt/8_asrt.jpg"></div>
			<h3>Касабланка</h3>
			<p>Роллы: Каталония, невада, мальта, коктебель, севастополь.</br><b class="veskal">1100 г., 1200 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>1300 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_2_asrt">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="2_asrt" />
			<input type="hidden" name="my-item-name" value="Скат" />
			<input type="hidden" name="my-item-price" value="975" />
			<input type="hidden" name="my-item-url" value="/catalog/asrt/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/asrt/2_asrt.jpg"></div>
			<h3>Скат</h3>
			<p>Роллы: лисий хвост, гейша, камикадзе, камчатка.</br><b class="veskal">863 г., 922 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>975 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_3_asrt">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="3_asrt" />
			<input type="hidden" name="my-item-name" value="Гольфстрим" />
			<input type="hidden" name="my-item-price" value="950" />
			<input type="hidden" name="my-item-url" value="/catalog/asrt/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/asrt/3_asrt.jpg"></div>
			<h3>Гольфстрим</h3>
			<p>Роллы: гейзер, темпура сан, мадагаскар. Суши: тобико, тобико черн., остры тунец, острая креветка.</br><b class="veskal">822 г., 969 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>950 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_4_asrt">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="4_asrt" />
			<input type="hidden" name="my-item-name" value="Дальний восток" />
			<input type="hidden" name="my-item-price" value="965" />
			<input type="hidden" name="my-item-url" value="/catalog/asrt/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/asrt/4_asrt.jpg"></div>
			<h3>Дальний восток</h3>
			<p>Роллы: калифорния с крабом, этна, спрут. Суши: осьминог. Дункан: токио.</br><b class="veskal">744 г., 823 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>965 р.</b></span>		
		</form>
	</li>
	<li>
		<form method="post" action="" class="jcart" id="Item_5_asrt">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="5_asrt" />
			<input type="hidden" name="my-item-name" value="Касатка" />
			<input type="hidden" name="my-item-price" value="1430" />
			<input type="hidden" name="my-item-url" value="/catalog/asrt/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/asrt/5_asrt.jpg"></div>
			<h3>Касатка</h3>
			<p>Роллы: самурай, морской ёж, калифорния, угорь в кунжуте, якудза, ясай.</br><b class="veskal">1246 г., 1307 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>1430 р.</b></span>		
		</form>
	</li>
	<li class="Bigger">
		<form method="post" action="" class="jcart" id="Item_6_asrt">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="6_asrt" />
			<input type="hidden" name="my-item-name" value="Big Fish" />
			<input type="hidden" name="my-item-price" value="1950" />
			<input type="hidden" name="my-item-url" value="/catalog/asrt/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/asrt/6_asrt.jpg"></div>
			<h3>Big Fish</h3>
			<p>Роллы: калифорния с лососём, спайс эби, приморье, фуджи, нью-йорк, чикаго, жемчужина, майами.</br><b class="veskal">1668 г., 1773 ккал</b></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>1950 р.</b></span>		
		</form>
	</li>
	<li class="Bigger">
		<form method="post" action="" class="jcart" id="Item_7_asrt">
			<input type="hidden" name="Token" value="<?php echo $_SESSION['jcartToken'];?>" />
			<input type="hidden" name="my-item-id" value="7_asrt" />
			<input type="hidden" name="my-item-name" value="Россия" />
			<input type="hidden" name="my-item-price" value="8250" />
			<input type="hidden" name="my-item-url" value="/catalog/asrt/" />
			<input class="qty" type="text" name="my-item-qty" value="1"/>
			<div><img src="/catalog/asrt/7_asrt.jpg"></div>
			<h3>Россия</h3>
			<p>Суши: тобико 2 шт., тобико чёрн. 2 шт., угорь, тунец, креветка, лосось, лосось копч., кальмар, окунь, икра, осьминог, остр. с тунцом, остр. с креветкой, токио. Роллы: лисий хвост, гейша, камикадзе, камчатка, самурай, морской ёж, калифорния, угорь в кунжуте, якудза, ясай, калифорния с лососем, спайс эби, приморье, фуджи, нью-йорк, чикаго, маймами, жемчужина, гейзер, темпура сан, мадагаскар,этна, калифорния с крабом, спрут.</br></p>
			<span><input type="submit" name="my-add-button" value=" " class="AddCart"/>Цена: <b>8250 р.</b></span>		
		</form>
	</li>
	
<br class="Clear" />	
</ul>
<!-- /ITEMS -->
</div>
<!-- /Block 1 -->
